Format 66


Style Acknowledgements
	Category              Other
	Margin                First_Dynamic
	LatexType             Environment
	LatexName             Acknowledgements
	NextNoIndent          1
	ResetArgs             1
	Argument 1
		LabelString    "Name"
		Tooltip        "Additional text appended to the theorem header"
	EndArgument
	LabelSep              xx
	ParIndent             MMM
	ParSkip               0.4
	ItemSep               0.2
	TopSep                0.7
	BottomSep             0.7
	ParSep                0.3
	Align                 Block
	AlignPossible         Left
	LabelType             Static
	LabelCounter          theorem
	LabelString           "Acknowledgements"
	Font
	  Family              Typewriter
	EndFont
	LabelFont
	  Series              Bold
	EndFont
	Requires              amsthm
End
