# Sets the order of the main theorem environments
# Author: Richard Heck
# modified by mathist

Format 66

#Get the order right
Style Theorem
End

Style Theorem*
End

Style Corollary
End

Style Corollary*
End

Style Lemma
End

Style Lemma*
End

Style Proposition
End

Style Proposition*
End

Style Conjecture
End

Style Conjecture*
End

Style Definition
End

Style Definition*
End

Style Example
End

Style Example*
End

Style Problem
End

Style Problem*
End

Style Exercise
End

Style Exercise*
End

Style Remark
End

Style Remark*
End

Style Claim
End

Style Claim*
End

#Style Proof
#End

#Style HINT
#End
